# Generated by Django 4.2.9 on 2025-12-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteScreen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
