# Generated by Django 4.2.9 on 2025-11-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountScreen', '0002_profile_address_profile_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phoneNumber',
            new_name='phonenumber',
        ),
        migrations.AddField(
            model_name='profile',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
