# Generated by Django 4.2.9 on 2025-11-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountScreen', '0003_rename_phonenumber_profile_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dateofbirth',
            new_name='date_of_birth',
        ),
    ]
