# Generated by Django 4.2.9 on 2025-11-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountScreen', '0004_rename_dateofbirth_profile_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
