# Generated by Django 4.2.9 on 2025-11-24 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountScreen', '0005_rename_phonenumber_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Số điện thoại phải ở định dạng: '+999999999'. Tối đa 15 chữ số.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
