# Generated by Django 4.2.9 on 2025-11-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('opening_hours', models.CharField(blank=True, default='', max_length=255)),
                ('rating', models.FloatField(default=4.0)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
