# Generated by Django 4.2.9 on 2025-11-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapScreen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
