# Generated by Django 4.2.9 on 2025-11-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapScreen', '0002_location_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
