# Generated by Django 4.2.9 on 2025-11-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapScreen', '0003_location_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='opening_hours',
            field=models.CharField(blank=True, default='24/7', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='tags',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
