# Generated by Django 4.2.9 on 2025-11-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapScreen', '0004_location_opening_hours_location_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='opening_hours',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
