# Generated by Django 4.2.9 on 2025-11-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreferenceScreen', '0002_alter_userpref_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpref',
            name='budgets',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userpref',
            name='eating_habits',
            field=models.JSONField(default=list),
        ),
    ]
