# Generated by Django 4.2.9 on 2025-11-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreferenceScreen', '0003_userpref_budgets_userpref_eating_habits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpref',
            name='activity_levels',
        ),
        migrations.RemoveField(
            model_name='userpref',
            name='budgets',
        ),
        migrations.RemoveField(
            model_name='userpref',
            name='group_types',
        ),
        migrations.AddField(
            model_name='userpref',
            name='activity_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userpref',
            name='budget',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userpref',
            name='group_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userpref',
            name='visit_duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='eating_habits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
