# Generated by Django 4.2.9 on 2025-11-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreferenceScreen', '0004_remove_userpref_activity_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpref',
            name='end_time',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userpref',
            name='start_time',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
